default_stages: [commit, merge-commit, push]
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
  - repo: git@github.com:PyCQA/autoflake.git
    rev: v2.0.2
    hooks:
      - id: autoflake
        stages: [commit]
        args: [--remove-all-unused-imports, --in-place, --ignore-init-module-imports]
  - repo: git@github.com:PyCQA/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit]
  - repo: git@github.com:psf/black.git
    rev: 22.8.0
    hooks:
      - id: black
        stages: [commit]
  - repo: git@github.com:PyCQA/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        stages: [commit, manual]
  - repo: git@github.com:dimaka-wix/commit-msg-hook.git
    rev: v0.3.4
    hooks:
      - id: commit-msg-hook
        stages: [commit-msg, prepare-commit-msg, manual]
  - repo: local
    hooks:
      - id: wheel-checker
        name: wheel-checker
        description: "Check Cython build wheel before every push"
        entry: bash build.sh
        language: system
        files: ''
        stages: [push, manual]
