# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../.."))


# -- Project information -----------------------------------------------------

project = "LinkeFL"
copyright = "2022, USTC LINKE Lab, Data Group, Federated Learning and Data Quality Team"
author = "USTC LINKE Lab, Data Group, Federated Learning and Data Quality Team"

# The full version, including alpha/beta/rc tags
import linkefl

release = linkefl.__version__


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "autoapi.extension",  # sphinx-autoapi
    "sphinx.ext.napoleon",  # numpy style docstring
    "myst_parser",  # support markdown
    "sphinx.ext.autodoc",  # load python source modules and generate API docs
    # 'sphinx.ext.viewcode', # view source code from the docs page
    "sphinx.ext.inheritance_diagram",
]

# configurations for 'autoapi.extension'
autoapi_type = "python"
autoapi_dirs = ["../../linkefl"]
autoapi_template_dir = "_autoapi_templates"
autodoc_typehints = "description"  # allow type hints
add_module_names = True
autoapi_options = [
    "members",
    "undoc-members",
    # 'private-members',
    "show-inheritance",
    "show-module-summary",
    # 'special-members',
    "imported-members",
]
# autoapi_add_toctree_entry = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster' # Sphinx default
# html_theme = 'furo'
html_theme = "pydata_sphinx_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
