name: Build Binary Wheels

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install Cython==3.0.0a11
          bash build.sh
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linkefl_wheels
          path: ./dist
